openapi: 3.0.0
info:
  title: Sample API
  description: An hypothetical API to serve as the base for POC applications to test various frameworks.
  version: 0.0.1
paths:
  /api/tokens:
    post:
      summary: Create Token
      description: Swap user credentials for a token to access the other APIs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "test@example.com"
                password:
                  type: string
                  example: "mysecretpassword"
              required:
                - email
                - password

      responses:
        '201':
          description: Create Token Response
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
                    description: A token to be passed as a Bearer Authorization header in all API calls.
                    example: "1!ZmRsO2ZzZGxmc2RsO3NzZGtmZDtlcnI7bHdrcmw7d2tybDs="
                  ttl:
                    type: integer
                    description: The token lifetime in seconds.
                    example: 3600
                  user_id:
                    type: string
                    description: A unique identifier for the user. To be passed in other user specific API requests in the URL.
                    example: "MTIzNDU2Nw=="



